def traducir(clave, idioma='es'):
    traducciones = {
        'es': {
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'telefono': 'Teléfono',
            'correo': 'Correo electrónico',
            'usuario': 'Nombre de usuario',
            'contrasena': 'Contraseña',
            'crear_usuario': 'Crear usuario',
            'volver': 'Volver',
            'campos_obligatorios': 'Faltan campos obligatorios',
            'usuario_creado': '¡Usuario creado con éxito!',
            'error': 'Error',
            'exito': 'Éxito',
            'asistente_predicacion': 'Asistente de Predicación',
            'sugerencias': 'Sugerencias',
            'temas_profundos': 'Temas Profundos',
            'buscar': 'Buscar',
            'cerrar_sesion': 'Cerrar sesión',
            'continuar': 'Entrar',
            'idioma': 'Idioma',
            'espanol': 'Español',
            'ingles': 'Inglés',
            'login': 'Iniciar sesión',
            'buscar_actualizaciones': 'Buscar actualizaciones',
            'recordar_usuario': 'Recordar usuario',
            'buscar_titulo': 'Buscar temas',
            'buscar_hint': 'Escribe una palabra clave...',
            'resultados': 'Resultados',
            'sin_resultados': 'No se encontraron coincidencias.',
        },
        'en': {
            'nombre': 'First Name',
            'apellido': 'Last Name',
            'telefono': 'Phone',
            'correo': 'Email',
            'usuario': 'Username',
            'contrasena': 'Password',
            'crear_usuario': 'Create user',
            'volver': 'Back',
            'campos_obligatorios': 'Missing required fields',
            'usuario_creado': 'User created successfully!',
            'error': 'Error',
            'exito': 'Success',
            'asistente_predicacion': 'Preaching Assistant',
            'sugerencias': 'Suggestions',
            'temas_profundos': 'Deep Topics',
            'buscar': 'Search',
            'cerrar_sesion': 'Log out',
            'continuar': 'Enter',
            'idioma': 'Language',
            'espanol': 'Spanish',
            'ingles': 'English',
            'login': 'Login',
            'buscar_actualizaciones': 'Check for updates',
            'recordar_usuario': 'Remember user',
            'buscar_titulo': 'Search Topics',
            'buscar_hint': 'Type a keyword...',
            'resultados': 'Results',
            'sin_resultados': 'No matches found.',
        }
    }

    return traducciones.get(idioma, traducciones['es']).get(clave, clave)